apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: mysql-pv-claim
    namespace: mysql
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    # FIXME: use the right IP
    server: 192.38.56.37
    path: /srv/mysql
